Lucas dos Anjos Moreira, senac tatuape, aprendendo git e github...
~= diretorio pessoal
ctrl + alt + t = terminal no ambiente grafico
ctrl + alt + f1 = terminal sem ambiente grafico
ls = listar arquivos e diretorios 
ls -lh = listar todos os diretorios detalhado
ctrl + l = limpar
cd + / = ir para a raiz do linux
cd = entrar nos diretorios
azul escuro = diretorio 
azul claro = link simbolico/atalho
cinza = arquivos
marca texto verda = perigo 
cd - = voltar 
pwd = verificar o diretorio 
mkdir = criar diretorio
&& = se o primeiro comando for executado com sucesso, o segundo será também
echo = para repetir 
touch = mudar data e hora do arquivo/criar arquivo 
cat = para listar o conteudo 
cat + -n = numero de linhas
head = para ver o começo do arquivo
head + -n = para escolher numero de linhas que voce quer ver 
tail = lista o final do arquivo 
tail -n20= para escolher o numero de linhas que voce quer ver
less= paginador 
Q = quit
| = saida de um comando é a entrada do outro 
